config/routes.rb
Rails.application.routes.draw do
  get 'public_reports/show'
  devise_for :users
  root to: "pages#dashboard"

  resources :clubs do
    resources :players
  end

  resources :games, except: [:new, :create] do
    resources :reports, only: [:create, :update]

    member do
      get :report, to: "reports#show"
    end
  end

  resources :reports, only: [:index] do
    resources :report_instances, only: [:create, :destroy]
  end

  resources :competitions do
    resources :games, only: [:new, :create]
  end

  resources :referees

  resources :public_reports, only: [:show, :update]
end

app/models/competition.rb
class Competition < ApplicationRecord
  acts_as_paranoid

  has_many :games, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController

  def index
    @competitions = Competition.order(created_at: :desc)
  end

  def new
    @competition = Competition.new
  end

  def create
    @competition = Competition.new(competition_params)

    if @competition.save
      redirect_to competitions_path, notice: "Competition created successfully"
    else
      render :new
    end
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def edit
    @competition = Competition.find(params[:id])
  end

  def update
    @competition = Competition.find(params[:id])

    if @competition.update(competition_params)
      redirect_to competitions_path, notice: "Competition updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    redirect_to competitions_path, notice: "Competition deleted successfully"
  end

  private

  def competition_params
    params.require(:competition).permit(:name)
  end
end

app/views/competitions/edit.html.erb
<div class="container">
  <%= simple_form_for @competition do |f| %>
    <%= f.input :name %>
    <%= f.submit class: "btn btn-success rounded-4" %>
  <% end %>

  <%= link_to "Back", competitions_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/competitions/index.html.erb
<div class="show-container">
  <div class="col-8">
    <div class="title-card col-12">
      <h1>Competitions List</h1>
    </div>
  <div class="col-12">
    <% @competitions.each do |competition| %>
      <%= link_to games_path(competition_id: competition.id), class: "referee-name" do%>
        <div class="match-card py-3 mb-2 mt-3">
          <div class="d-flex justify-content-between align-items-center mx-5">
            <h6 class="mb-0">
              <span style="color: white;"><%= competition.name %></span>
              <span style="color: white;">|</span>
              <span style="color: white;"><%= competition.created_at.strftime('%d-%m-%Y') %></span>
            </h6>
            <%= link_to "+ info", competition_path(competition), class: "btn btn-success rounded-5" %>
            <%#= link_to "Edit",  edit_competition_path(competition), class: "text-decoration-none btn btn-primary btn-sm rounded-4 mr-2" %>
            <%#= link_to "Delete", competition_path(competition), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none btn btn-outline-danger btn-sm rounded-4 mr-2" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
    <p class="mt-4 col-12"><%= link_to "Add Competition", new_competition_path, class: "btn btn-success rounded-4 col-12" %></p>
  </div>
</div>

app/views/competitions/new.html.erb
<div class="show-container d-flex align-item-middle justify-content-center">
  <div class="form-group-container col-8 px-5">

    <%= simple_form_for @competition do |f| %>
        <%= f.input :name %>
        <%= f.submit 'Create Competititon', class: "btn btn-success rounded-5" %></p>
    <% end %>

    <%= link_to 'Back', competitions_path, class: "btn btn-danger rounded-5 mt-3" %>

  </div>
</div>

app/views/competitions/show.html.erb
<div class="container">
  <%= @competition.name %>
  <%= @competition.created_at.strftime('%d-%m-%Y') %>

  <%= link_to "Edit", edit_competition_path(@competition) %> |
  <% if current_user.role != "referee" %>
    <%= button_to "Delete", competition_path(@competition), method: :delete, data: {turbo_confirm: "Are you sure?"} %>
  <% end %>
  <%= link_to "Back", competitions_path %>
</div>