config/routes.rb
Rails.application.routes.draw do
  get 'public_reports/show'
  devise_for :users
  root to: "pages#dashboard"

  resources :clubs do
    resources :players
  end

  resources :games, except: [:new, :create] do
    resources :reports, only: [:create, :update]

    member do
      get :report, to: "reports#show"
    end
  end

  resources :reports, only: [:index] do
    resources :report_instances, only: [:create, :destroy]
  end

  resources :competitions do
    resources :games, only: [:new, :create]
  end

  resources :referees

  resources :public_reports, only: [:show, :update]
end

app/views/shared/_final_report.html.erb
<div class="teams-report-container" data-submit-form-reports-target="report">
  <div class="team-report">
    <%= game.club_home.abbreviation %>
    <%= render "shared/final_report_clubs", report: report, report_instance: report_instance, players: game.club_home.players, game: game  %>
  </div>

  <div class="team-report">
    <%= game.club_away.abbreviation %>
    <%= render "shared/final_report_clubs", report: report, report_instance: report_instance, players: game.club_away.players, game: game  %>
  </div>
</div>

<div class="report-infos-container px-3">
  <p>Match report</p>
  <% report.report_instances.where(category: "Other").each do |instance| %>
    <p><%= instance.motive %></p>
  <% end %>

  <%= simple_form_for [report, report_instance],
                      data: { submit_form_reports_target: "instanceForm" },
                      html: { class: "report-form #{"d-none" if report.referee_validation}" } do |f| %>
    <%= f.input :category, as: :hidden, input_html: { value: "Other" } %>

    <%# CAIXA TEXTO %>
    <%= f.input :motive, label: false, input_html: { class: "m-0 p-2 rounded-4", placeholder: "Enter your observations here" }%>
  <% end %>
</div>



  <%= simple_form_for [game, report],
                      data: {
                        submit_form_reports_target: "reportForm",
                        action: "submit->submit-form-reports#submitForms"
                      },
                      html: { class: "report-form #{"d-none" if report.referee_validation}" } do |f| %>
    <%= f.input :referee_validation %>
    <span class="d-display justify-content-centered">
      <%= f.submit "Generate Report", class:"btn btn-success rounded-4 col-12 mx-1" %>
    </span>
  <% end %>
</div>

app/views/shared/_final_report_clubs.html.erb
<table class="teams-table w-100">
      <% players.each do |player| %>
        <tr class="">
          <td class="border-right-table-row w-60px"><%= player.player_number %></td>
          <td class="text-start px-2 player-names"><%= player.first_name %> <%= player.last_name %></td>
          <td class="instances text-start gap-1">
            <% player.report_instances.where(report: report).order(minute: :asc).each do |report_instance| %>
              <p class="m-0"><%#= report_instance.category %></p>
              <% case %>
                <% when report_instance.category == "Own-Goal" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: red;"></i></p>
                <% when report_instance.category == "Goal" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: green;"></i></p>
                <% when report_instance.category == "Green-Card" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-play" style="color: green; transform: rotate(31deg); padding-top: 7px; padding-left: 3px;"></i></p>
                <% when report_instance.category == "Yellow-Card" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-square" style="color: #ffed00;"></i></p>
                <% when report_instance.category == "Red-Card" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-circle" style="color: #E73632;"></i></p>
                <% when report_instance.category == "Sub-In" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: green;"></i></p>
                <% when report_instance.category == "Sub-Out" %>
                <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: #E73632;"></i></p>
              <% end %>
            <% end %>
          </td>
          <td class="w-40px"> <%= check_box_tag "selected_players[]", player.id %> </td>
          <td class="add-intances-buttons <%= "d-none" if report.referee_validation %>">
            <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#modalPlayer-<%= player.id %>">
              <i class="fa-solid fa-circle-plus"></i>
            </button>
            <%= render "shared/form_report_player_instance", report: report, report_instance: report_instance, player: player, game: game  %>
          </td>
        </tr>
      <% end %>
    </table>

app/views/shared/_final_report_clubs_email.html.erb
<table class="teams-table w-100 rounded-5">
  <% players.each do |player| %>
    <tr class="">
      <td class="border-right-table-row w-60px"><%= player.player_number %></td>
      <td class="text-start px-2 player-names"><%= player.first_name %> <%= player.last_name %></td>
      <td class="instances text-start gap-1">
        <% player.report_instances.where(report: report).order(minute: :asc).each do |report_instance| %>
          <p class="m-0"><%#= report_instance.category %></p>
          <% case %>
            <% when report_instance.category == "Own-Goal" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: red;"></i></p>
            <% when report_instance.category == "Goal" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: green;"></i></p>
            <% when report_instance.category == "Green-Card" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-play" style="color: green; transform: rotate(31deg); padding-top: 7px; padding-left: 3px;"></i></p>
            <% when report_instance.category == "Yellow-Card" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-square" style="color: #ffed00;"></i></p>
            <% when report_instance.category == "Red-Card" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-circle" style="color: #E73632;"></i></p>
            <% when report_instance.category == "Sub-In" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: green;"></i></p>
            <% when report_instance.category == "Sub-Out" %>
            <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: #E73632;"></i></p>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/_final_report_email.html.erb
<div class="teams-report-container" data-submit-form-reports-target="report">
  <div class="team-report">
    <%= @report.game.club_home.abbreviation %>
    <%= render "shared/final_report_clubs_email", report: report, players: report.game.club_home.players %>
  </div>

  <div class="team-report">
    <%= @report.game.club_away.abbreviation %>
    <%= render "shared/final_report_clubs_email", report: report, players: report.game.club_away.players %>
  </div>
</div>

<div class="report-infos-container px-3">
  <p>Match report</p>
  <% @report.report_instances.where(category: "Other").each do |instance| %>
    <p><%= instance.motive %></p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form_modal_match.html.erb
<div class="modal fade text-center" id="<%= modal_id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog model-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" style="color: black;" id="exampleModalLabel">Create Match</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"  style= "color: black;">
        <%= competition.name %>
        <p></p>
        <%#= competition.created_at.strftime('%d-%m-%Y') %>

        <%= link_to "Create a Match", new_competition_game_path(competition), class: "btn btn-primary mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_report_player_instance.html.erb
<div class="modal fade" id="modalPlayer-<%= player.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog model-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <%# <h1 class="modal-title fs-5" id="exampleModalLabel"></h1> %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3><%= "#{player.first_name} #{player.last_name}" %></h3>
        <%= simple_form_for [report, report_instance] do |f| %>
          <%= f.input :player_id, as: :hidden, input_html: { value: player.id } %>
          <%= f.input :category, collection: ReportInstance::REPORT_INSTANCES_CATEGORIES, label: 'Category:' %>
          <%= f.input :minute, as: :integer %>
          <span class="d-display justify-content-centered"><%= f.submit "Add", class:"btn btn-success rounded-4 col-12 mx-1" %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_info_window.html.erb
<h2 style="color: black"><%= game.club_home.name %></h2>
<p style="color: black"><%= game.club_home.address %></p>

app/views/shared/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/shared/_navbar.html.erb
<nav>
  <ul class="nav-list">
      <li class="nav-item">
        <%= link_to root_path do %>
        <div class="logo">
          <%= image_tag "sportsadmin-whitelogo.svg", class: "nav-item-icon" %>
          <span class="nav-item-text">Sports Admin</span>
        </div>
      </li>
      <% end %>
    </a>
    <li class="nav-item">
      <%= link_to root_path do %>
        <i class="fa-solid fa-house nav-item-icon"></i>
        <span class="nav-item-text">Home</span>
      <% end %>
      </a>
    </li>
    <li class="nav-item">
      <%= link_to games_path do %>
        <i class="fa-solid fa-calendar nav-item-icon"></i>
        <span class="nav-item-text">Calendar</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to referees_path do %>
        <i class="fa-solid fa-user nav-item-icon"></i>
        <span class="nav-item-text">Referees</span>
      <% end %>
      </a>
    </li>
    <li class="nav-item">
      <%= link_to competitions_path do %>
        <i class="fa-solid fa-trophy nav-item-icon"></i>
        <span class="nav-item-text">Competitions</span>
      <% end %>
      </a>
    </li>
    <li class="nav-item">
      <%= link_to clubs_path do %>
        <i class="fa-solid fa-people-group nav-item-icon"></i>
        <span class="nav-item-text">Clubs</span>
        <% end %>
      </a>
    </li>
    <li class="nav-item">
      <%= link_to reports_path do %>
        <i class="fa-solid fa-clipboard-list nav-item-icon"></i>
        <span class="nav-item-text">Reports</span>
      <% end %>
      </a>
    </li>
    <li class="nav-item logout">
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <i class="fa-solid fa-right-from-bracket nav-item-icon"></i>
        <span class="nav-item-text"> Log out</span>
      <% end %>
      </a>
    </li>
  </ul>
</nav>

app/views/shared/_new_final_report.html.erb
<div data-submit-form-reports-target="report">

    <%# LINE UP  BEGIN %>

    <div class="mx-3">
    <div class="simple-list-row d-flex align-items-start justify-content-around m-0 p-0 col-12">


      <div class="simple-list d-flex align-items-start justify-content-start m-0 p-0 col-6">
        <div class="list-group rounded-4 col-12 mb-4">
          <button type="button" class="list-group-item list-group-item-action-none active d-flex justify-content-start mb-1" aria-current="true"><span class="text-success ms-3 me-1"><%= game.club_home.abbreviation %></span> Line-Up</button>
          <% game.club_home.players.each do |player| %>

            <div class="list-group-item list-group-item-action d-flex align-items-center mb-1 col-12">
              <p class="col-1 mb-0 d-flex justify-content-end"><span class="text-success"><%= player.player_number %></p></span>
              <p class="p-small col-7 text-nowrap m-0"><span class="mx-2"></span> <%= player.full_name %></p>
              <div class="col-4 d-flex justify-content-end align-items-center stats">
                <% player.report_instances.where(report: report).order(minute: :asc).each do |report_instance| %>
                  <p class="mx-1"></p>
                  <% case %>
                    <% when report_instance.category == "Own-Goal" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: #ef233c;"></i></p>
                    <% when report_instance.category == "Goal" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: #5af7dc;"></i></p>
                    <% when report_instance.category == "Green-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-play" style="color: #89fc00; transform: rotate(31deg); padding-top: 7px; padding-left: 3px;"></i></p>
                    <% when report_instance.category == "Yellow-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-square" style="color: #ffed00;"></i></p>
                    <% when report_instance.category == "Red-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-circle" style="color: #ef233c;"></i></p>
                    <% when report_instance.category == "Sub-In" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: green;"></i></p>
                    <% when report_instance.category == "Sub-Out" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: #ef233c;"></i></p>
                  <% end %>
                <% end %>

                <button type="button m-0 p-0" class="btn m-0 p-0" data-bs-toggle="modal" data-bs-target="#modalPlayer-<%= player.id %>">
                  <i class="fa-solid fa-circle-plus mx-2 p-0"></i>
                </button>
              </div>
            </div>
            <div class="rounded-bottom-5"><%= render "shared/form_report_player_instance", report: report, report_instance: report_instance, player: player, game: game %></div>
          <% end %>
        </div>
      </div>

      <%# AWAY TEAM %>

      <div class="simple-list d-flex align-items-start justify-content-start m-0 p-0 col-6">
        <div class="list-group rounded-4 col-12 mb-4">
          <button type="button" class="list-group-item list-group-item-action-none active d-flex justify-content-start mb-1" aria-current="true"><span class="text-danger ms-3 me-1"><%= game.club_away.abbreviation %></span> Line-Up</button>
          <% game.club_away.players.each do |player| %>
            <div class="list-group-item list-group-item-action d-flex align-items-center mb-1 col-12">
              <p class="col-1 mb-0 d-flex justify-content-end"><span class="text-danger"><%= player.player_number %></p></span>
              <p class="p-small col-7 text-nowrap m-0"><span class="mx-2"></span> <%= player.full_name %></p>
              <div class="col-4 d-flex justify-content-end align-items-center stats">
                <% player.report_instances.where(report: report).order(minute: :asc).each do |report_instance| %>
                  <p class="mx-1"></p>
                  <% case %>
                    <% when report_instance.category == "Own-Goal" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: #ef233c;"></i></p>
                    <% when report_instance.category == "Goal" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-regular fa-futbol" style="color: #5af7dc;"></i></p>
                    <% when report_instance.category == "Green-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-play" style="color: #89fc00; transform: rotate(31deg); padding-top: 7px; padding-left: 3px;"></i></p>
                    <% when report_instance.category == "Yellow-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-square" style="color: #ffed00;"></i></p>
                    <% when report_instance.category == "Red-Card" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-circle" style="color: #ef233c;"></i></p>
                    <% when report_instance.category == "Sub-In" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: green;"></i></p>
                    <% when report_instance.category == "Sub-Out" %>
                    <p class="m-0" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= report_instance.minute %>' - <%= report_instance.category %>"><i class="fa-solid fa-rotate" style="color: #ef233c;"></i></p>
                  <% end %>
                <% end %>

                <button type="button m-0 p-0" class="btn m-0 p-0" data-bs-toggle="modal" data-bs-target="#modalPlayer-<%= player.id %>">
                  <i class="fa-solid fa-circle-plus mx-2 p-0"></i>
                </button>
              </div>
            </div>
            <div>
              <%= render "shared/form_report_player_instance", report: report, report_instance: report_instance, player: player, game: game %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
</div>
<div class="simple-list d-flex align-items-start justify-content-start m-0 p-0 col-12">
      <div class="match-card col-12 m-0 p-0 rounded-4 mb-5">
        <div class="list-group rounded-4 col-12 mb-0">

          <button type="button" class="list-group-item list-group-item-action-none active mb-1" aria-current="true">
            <span class="text-success"><%= game.club_home.abbreviation %></span>
            vs
            <span class="text-danger"><%= game.club_away.abbreviation %></span>
            Report
          </button>

          <%game.report.report_instances.where(category: "Other").each do |instance| %>
            <p><%= instance.motive %></p>
          <% end %>

          <%= simple_form_for [game.report, report_instance],
                      data: { submit_form_reports_target: "instanceForm" },
                      html: { class: "report-form #{"d-none" if game.report.referee_validation}" } do |instance_form| %>
            <%= instance_form.input :category, as: :hidden, input_html: { value: "Other" } %>

            <div class="mx-3">

                <%# CAIXA TEXTO %>
                <%= instance_form.input :motive, label: false, input_html: { class: "m-0 p-2 rounded-4", placeholder: "Enter your observations here" }%>
              <% end %>

                <div class="d-flex align-items-center justify-content-center btn btn-primary rounded-top-4 rounded-bottom-4 m-0 mb-3 pt-3 p-0 col-12">
                  <%= simple_form_for [game, game.report],
                              data: {
                                submit_form_reports_target: "reportForm",
                                action: "submit->submit-form-reports#submitForms"
                              },
                              html: { class: "report-form #{"d-none" if game.report.referee_validation}" } do |report_form| %>
                    <%# REFEREE VALIDATION %>
                    <%= report_form.input :referee_validation, class: "d-flex align-items-center col-4 m-0 p-0 rounded-5", input_html: { class: "d-flex align-items-center bg-danger rounded-5" } %>
                </div>

            </div>

            <%# GENERATE REPORT %>
              <span class="d-flex justify-content-center"><%= report_form.submit "Generate Report", class:"btn btn-danger rounded-top-0 rounded-bottom-4 mt-3 col-12" %></span>
            <% end %>
        </div>
      </div>
    </div>