config/routes.rb
Rails.application.routes.draw do
  get 'public_reports/show'
  devise_for :users
  root to: "pages#dashboard"

  resources :clubs do
    resources :players
  end

  resources :games, except: [:new, :create] do
    resources :reports, only: [:create, :update]

    member do
      get :report, to: "reports#show"
    end
  end

  resources :reports, only: [:index] do
    resources :report_instances, only: [:create, :destroy]
  end

  resources :competitions do
    resources :games, only: [:new, :create]
  end

  resources :referees

  resources :public_reports, only: [:show, :update]
end

app/models/player.rb
class Player < ApplicationRecord
  acts_as_paranoid

  belongs_to :club
  has_many :report_instances

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :player_number, presence: true, length: { in: 0..99 }
  validates :gender, presence: true, inclusion: { in: %w[male female other] }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_club, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def new
    @player = Player.new
  end

  def create
    @player = @club.players.build(player_params)

    if @player.save
      redirect_to club_path(@club), notice: 'Player created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @players = @club.players || []
  end

  def show
  end

  def edit
  end

  def update
    if @player.update(player_params)
      redirect_to club_player_path(@club, @player), notice: 'Player updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @player.destroy
    redirect_to club_players_path(@club), notice: 'Player deleted'
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:first_name, :last_name, :birth_date, :gender, :player_number)
  end
end

app/views/players/edit.html.erb
<div class="container">

  <%= simple_form_for [@club, @player] do |f| %>
    <%= f.input :player_number %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'Back', club_path(@club), class: "btn btn-secondary mt-3" %>

</div>

app/views/players/index.html.erb
 <div class="main-container">
      <div class="games-container">
      <span class="title-matches"><h1>Players List  - <%= cl_image_tag @club.photo.key, height: 30, width: 30, crop: :fill, class: "rounded-top-4 me-2 mr-1", style: "background-color: white;" %><%= @club.name %></h1></span>

        <% @players.each do |player| %>

            <div class="games-card py-3 mb-2 mt-3"><%= link_to club_player_path(@club, player), class: "referee-name" do %>
              <div class="d-flex justify-content-between align-items-center mx-5">
                <h6 class="referee-name mb-0">
                  <%= player.full_name %> - Number: <%= player.player_number %>
                </h6>
                <div class="d-flex">
                  <span class= "btn btn-success rounded-4">+ info</span>
                  <%#= link_to "+ info", club_player_path(@club, player), class: "btn btn-success rounded-4" %>
                  <%#= link_to "Edit",  edit_competition_path(competition), class: "text-decoration-none btn btn-primary btn-sm rounded-4 mr-2" %>
                  <%#= link_to "Delete", competition_path(competition), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none btn btn-outline-danger btn-sm rounded-4 mr-2" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <p class="mt-4"><%= link_to "Add Player", new_club_player_path(@club), class: "btn btn-success rounded-4" %></p>
</div>

app/views/players/new.html.erb
<div class="container">

  <%= simple_form_for [@club, @player] do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :player_number %>
    <%= f.input :birth_date %>
    <%= f.input :gender, collection: %w[male female other] %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'Back', club_path(@club), class: "btn btn-secondary mt-3" %>

</div>

app/views/players/show.html.erb
<div class="container">

  <h1><%= @player.full_name %></h1>
  <p><strong>Player Numnber:</strong> <%= @player.player_number %></p>
  <p><strong>Birth Date:</strong> <%= @player.birth_date %></p>
  <p><strong>Gender</strong> <%= @player.gender %></p>

  <%= link_to "Edit", edit_club_player_path(@club, @player) %> |
  <% if current_user.role != "referee" %>
    <%= button_to "Delete", club_player_path(@club, @player), method: :delete, data: {turbo_confirm: "Are you sure?"} %>
  <% end %>
  <%= link_to 'Back', club_path(@club), class: "btn btn-secondary mt-3" %>

</div>