config/routes.rb
Rails.application.routes.draw do
  get 'public_reports/show'
  devise_for :users
  root to: "pages#dashboard"

  resources :clubs do
    resources :players
  end

  resources :games, except: [:new, :create] do
    resources :reports, only: [:create, :update]

    member do
      get :report, to: "reports#show"
    end
  end

  resources :reports, only: [:index] do
    resources :report_instances, only: [:create, :destroy]
  end

  resources :competitions do
    resources :games, only: [:new, :create]
  end

  resources :referees

  resources :public_reports, only: [:show, :update]
end

app/controllers/referees_controller.rb
  class RefereesController < ApplicationController
    before_action :set_referee, only: [:show, :edit, :update, :destroy]

    def index
      @referees = User.referee
    end

    def show
      @games = Game.where(referee_id: params[:id])
    end

    def new
      @referee = User.new
    end

    def create
      @referee = User.new(referee_params)
      @referee.role = "referee"
      if @referee.save
        redirect_to referees_path, notice: "Referee created"
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @referee.update(referee_params)
        redirect_to referee_path(@referee), notice: "Referee was successfully updated."
      else
        render :edit
      end
    end

    def destroy
      @referee.destroy
      redirect_to referees_path, notice: "Referee was successfully destroyed."
    end

    private

    def referee_params
      params.require(:user).permit(:first_name, :last_name, :birth_date, :email, :phone_number, :city, :password, :password_confirmation)
    end

    def set_referee
      @referee = User.find(params[:id])
    end
  end

app/views/referees/edit.html.erb
<div class="container">
  <h1>Edit Referee</h1>

  <%= form_with model: @referee, url: referee_path(@referee), data: { turbo_method: "PATCH" } do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>

    <%= f.submit "Update Referee", class: "btn btn-primary" %>

    <% if @referee.errors.any? %>
      <div class="alert alert-danger">
        <h4>Errors:</h4>
        <ul>
          <% @referee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <%= link_to "Back", referee_path(@referee), class: "btn btn-secondary mt-3" %>
</div>

app/views/referees/index.html.erb
<div class="show-container">
  <div class="col-8">
    <div class="title-card col-12">
      <h1>Referee's List</h1>
    </div>
  <div class="col-12">
    <% @referees.each do |referee| %>
      <%= link_to referee_path(referee), class: "referee-name" do %>
        <div class="match-card py-3 mb-2 mt-3">
          <div class="d-flex justify-content-between align-items-center mx-5">
            <h6 class="text-decoration-none mb-0"><%= referee.full_name %></h6>
           <!-- <span class= "btn btn-success rounded-4">+ info</span> -->
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
    <p class="mt-4 col-12"><%= link_to "Add Referee", new_referee_path, class: "btn btn-success rounded-4 col-12" %></p>
  </div>
</div>

app/views/referees/new.html.erb
<div class="show-container">

  <div class="form-group-container col-8 p-5">
    <h1>New Referee</h1>

    <%= form_with model: @referee, url: referees_path, data: { turbo_method: "POST" } do |f| %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :birth_date %>
        <%= f.date_field :birth_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Create Referee', class: 'btn btn-primary' %>
    <% end %>

    <% if @referee.errors.any? %>
      <div class="alert alert-danger mt-3">
        <h4 class="alert-heading">There were some errors with your submission:</h4>
        <ul>
          <% @referee.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= link_to 'Back', referees_path, class: "btn btn-danger mt-3 rounded-4" %>
  </div>
</div>

app/views/referees/show.htm.erb
<h1><%= @referee.full_name %></h1>
<p><strong>Email:</strong> <%= @referee.email %></p>
<p><strong>Phone:</strong> <%= @referee.phone_number %></p>
<%= link_to "Edit", edit_referee_path(@referee) %> |
<%= button_to "Delete", referee_path(@referee), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to "Back", referees_path %>

app/views/referees/show.html.erb
<div class="show-container">

  <div class="title-card col-8">
    <span class="d-flex justify-content-between align-items-center"><h1><%= @referee.full_name %>'s Profile </h1>
      <%= link_to 'Back', referees_path, class: "btn btn-success rounded-pill mb-3" %>
    </span>
  </div>

  <div class="show-two-column-container col-12 gap-3">

    <div class="simple-card d-flex align-items-center justify-content-center m-0 p-4 col-3">
      <span><%= image_tag "noun-referee-1817217-01.svg", class: "profile-default mt-2"%></span>
      <h3><%= @referee.first_name %></h3>
      <h3><%= @referee.last_name %></h3>
      <p class="p-highlight mt-4 mb-1">Email</p>
      <h5><%= @referee.email %></h5>
      <p class="p-highlight mt-4 mb-1">Phone No.</p>
      <h5><%= @referee.phone_number %></h5>
      <span class="btn btn-success mt-3 rounded-4 col-12"><%= link_to "Edit", edit_referee_path(@referee) %></span>
      <% if current_user.role != "referee" %>
        <span class="btn btn-danger mt-3 rounded-4 col-12"><%= link_to "Delete", referee_path(@referee), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></span>
      <% end %>
    </div>

    <div class="simple-list d-flex align-items-start justify-content-start m-0 p-0 col-5">

      <div class="list-group rounded-4 col-12 mb-4">
        <button type="button" class="list-group-item list-group-item-action-none active mb-1" aria-current="true"><%= @referee.full_name %>'s Upcoming Matches</button>
        <% @games.where("game_date >= ?", (DateTime.now + 1.day).all_day).each do |game| %>
          <%= link_to game_path(game), class: "list-group-item list-group-item-action mb-1" do %>
            <%= "#{game.club_home.abbreviation} vs #{game.club_away.abbreviation} - #{game.game_date.strftime("%-d %b, %k:%M")}" %>
          <% end %>
        <% end %>
      </div>

      <div class="list-group rounded-4 col-12">
        <button type="button" class="list-group-item list-group-item-action-none active mb-1" aria-current="true"><%= @referee.full_name %>'s Reports</button>
        <% @games.where("game_date < ?", DateTime.now.all_day).each do |game| %>
          <%= link_to report_game_path(game), class: "list-group-item list-group-item-action mb-1" do %>
            <%= "#{game.club_home.abbreviation} vs #{game.club_away.abbreviation} - #{game.game_date.strftime("%-d %b, %k:%M")}" %>
          <% end %>
        <% end %>
      </div>

    </div>

  </div>
</div>